# Generated by Django 5.1.1 on 2024-10-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:/Podkorytro01/Netology/Django/dj-homeworks/3.1-drf-intro/smart_home/', verbose_name='Изображение'),
        ),
    ]
