# Generated by Django 5.1.1 on 2024-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Модель')),
                ('price', models.CharField(max_length=6, verbose_name='Цена')),
                ('image', models.URLField(max_length=250, verbose_name='Фото')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField(verbose_name='Наличие LTE')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
